# Importing Necessary Libraries

In [1]:
#pip install Tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
#Tensorflow is an open-source high performance package for deep learning invented by Google

In [4]:
tf.__version__

'2.9.1'

In [5]:
#Tensor flow  is basically dealt with 2 different features namely :1)constants(inputs and outputs) 2)variables(weights and bias)

### Constants

In [6]:
a = tf.constant([[1,2],[3,4]])

In [7]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
b = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [9]:
m = tf.constant([[1,2,3,4],[5,6,7,8]])
n = tf.constant([[9,10,11,12],[1,5,3,6]])

In [10]:
print(m+n)

tf.Tensor(
[[10 12 14 16]
 [ 6 11 10 14]], shape=(2, 4), dtype=int32)


In [11]:
m-n

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[-8, -8, -8, -8],
       [ 4,  1,  4,  2]])>

In [12]:
m*n

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 9, 20, 33, 48],
       [ 5, 30, 21, 48]])>

In [13]:
m/n

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [5.        , 1.2       , 2.33333333, 1.33333333]])>

In [14]:
x = tf.constant([[1,2,1],[2,3,2],[4,5,3]])
y = tf.constant([[0,4,4],[5,5,-1],[6,2,6]])
x*y # element wise multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 0,  8,  4],
       [10, 15, -2],
       [24, 10, 18]])>

In [15]:
x@y #matrix multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 16,  8],
       [27, 27, 17],
       [43, 47, 29]])>

In [16]:
#stacking

In [17]:
p = tf.constant([1,2,3])
q = tf.constant([4,6,7])

In [18]:
r = tf.stack([p,q])
r

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 6, 7]])>

In [19]:
#slicing

In [20]:
o = tf.constant([[1,2,3],[4,5,6]])
o

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [21]:
o[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>

In [22]:
o[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [23]:
o[0,0:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [24]:
o[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [25]:
o[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>

In [26]:
o[1,1:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6])>

In [27]:
o[1,1:2]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>

In [28]:
o[1,0:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5])>

In [29]:
#reshaping

In [30]:
o = tf.constant([1,2,4])

In [31]:
p = tf.reshape(o,[3,1])

In [32]:
p

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [4]])>

In [33]:
#using reduce function

In [34]:
q = tf.constant([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

In [35]:
tf.reduce_max(q)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [36]:
tf.reduce_min(q)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [37]:
tf.reduce_mean(q)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [38]:
tf.reduce_sum(q)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [39]:
tf.reduce_prod(q)

<tf.Tensor: shape=(), dtype=int32, numpy=331776>

In [40]:
u = tf.constant([1,2,3,4,10,5,6])
tf.argmax(u)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [41]:
#Variable

In [42]:
a = tf.Variable([[1,2,3],[2,3,4],[3,4,5]])

In [43]:
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [44]:
#Building a simple network

In [45]:
x=tf.constant([[1.0,2.4,4.1,5.8],[1.7,2.7,3.6,4.7],[1.1,2.8,3.6,4.9]])
y=tf.constant([[1.4,2.5],[1.7,2.6],[1.4,2.9]])

In [46]:
neurons_x = 4
neurons_hidden = 3
neurons_y = 2

In [47]:
weights = {'w1':tf.Variable(tf.random.truncated_normal([neurons_x,neurons_hidden], stddev=0.1)),
           'w2':tf.Variable(tf.random.truncated_normal([neurons_hidden,neurons_y], stddev=0.1))}
        

In [48]:
weights['w1']

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.05655786,  0.02257664,  0.13609505],
       [-0.01663238, -0.11523447, -0.1195722 ],
       [ 0.06099253,  0.04045695,  0.01274492],
       [-0.02630155, -0.03960369,  0.04093237]], dtype=float32)>

In [49]:
weights['w2']

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.14053984,  0.03903952],
       [-0.1750627 , -0.09107336],
       [-0.0162971 ,  0.12449051]], dtype=float32)>

In [50]:
bias={'b1':tf.Variable(tf.constant([1.0],shape=[neurons_hidden])),'b2':tf.Variable(tf.constant([1.0],shape=[neurons_y]))}

In [51]:
bias['b1']

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [52]:
bias['b2']

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [53]:
x_hidden=tf.nn.sigmoid(tf.add(tf.matmul(x,weights['w1']),bias['b1']))

In [54]:
x_hidden

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7529039 , 0.6642264 , 0.7574562 ],
       [0.7589985 , 0.66524464, 0.75892234],
       [0.75144583, 0.6578584 , 0.74294895]], dtype=float32)>

In [56]:
y_pred=tf.nn.tanh(tf.add(tf.matmul(x_hidden,weights['w2']),bias['b2']))

In [57]:
y_pred

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7518458 , 0.78688395],
       [0.7521301 , 0.78700876],
       [0.7523437 , 0.7863949 ]], dtype=float32)>

In [58]:
y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.4, 2.5],
       [1.7, 2.6],
       [1.4, 2.9]], dtype=float32)>

In [59]:
tf.losses.categorical_crossentropy(y,y_pred)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.679233 , 2.9612386, 2.9483867], dtype=float32)>

In [60]:
tf.reduce_mean(tf.losses.categorical_crossentropy(y,y_pred))

<tf.Tensor: shape=(), dtype=float32, numpy=2.8629525>